# == Zuul configuration file ==
#
# This file is used to configure this project and its associated jobs in Zuul.
# Zuul is the CI/CD tool which lets us check changes before they are committed,
# and build a canary version of the extension on a regular basis.
#
# More info about Zuul: https://zuul-ci.org/docs/zuul/

- job:
    name: translateselectedtext-lint
    parent: base
    pre-run: playbooks/lint/pre.yaml
    run: playbooks/lint/run.yaml
    roles:
      - zuul: zuul/jobs
    irrelevant-files:
      - ".github/.*"
      - "docs/.*"
      - "OWNERS"
      - "README.md"
      - "roles/cws-publish/*"
      - "playbooks/nightly-build/*"

- job:
    name: translateselectedtext-test-nightly-build
    pre-run: playbooks/nightly-build/pre.yaml
    run: playbooks/nightly-build/test.yaml
    roles:
      - zuul: zuul/jobs
    vars:
      credentials:
        clientId: "testClientId"
        refreshToken: "testRefreshToken"
    files:
      - "roles/cws-publish/*"
      - "playbooks/nightly-build/*"

- job:
    name: translateselectedtext-nightly-build
    attempts: 1
    pre-run: playbooks/nightly-build/pre.yaml
    run: playbooks/nightly-build/run.yaml
    post-run: playbooks/nightly-build/post.yaml
    roles:
      - zuul: zuul/jobs
    secrets:
      - name: credentials
        secret: credentials_tst

- project:
    check:
      jobs:
        - translateselectedtext-test-nightly-build
        - translateselectedtext-lint
    nightly-build:
      jobs:
        - translateselectedtext-nightly-build

# Secrets generated via https://github.com/fregante/chrome-webstore-upload-keys
- secret:
    name: credentials_tst
    data:
      clientId: !encrypted/pkcs1-oaep
        - LxIyoMwiy6JXbDFcvGkk78joHg0kOgzV8W76ojR2Fcdf4bZm/TQX+Dod5QxhqbQjrSMsn
          rsuAHs4Mj9EUoHeftofFdJ19xQKeM+m3AY9UeHnwtxPVEWl385fCOgmiCbq1Dgk7lLLKN
          8+6M9dXM6jcMzzsHSdswwPjPnKVH9dkZ7rJD3bY97ICSDkd9N21CaxCSWnFkeY0QVf9Na
          Gv/DojUy0nHL6Rn2J5t8LC8fMKcEV+WBB/oICW3A30/MxcAweRz3pWMCh57aS0vtT8ckk
          yAGTm3Zb8jNjtgcOJBsFlyHutBS4evadKxJozl5V/V/rnhozQz5XXkx58OzXDs1JL9TaE
          IFneMvsICt/cWLjeivtlD/Ik70t1b5G5wdWF7Wfxocc+3knncNSlCOuoWwQUc+vZxGzYO
          b92akIrOtbAj79X7p2lAr2mpiJqTi8ovYQrt4GiRzGvsfHbrTDfXV3J13H5Sojx5PTKyR
          Wf+8GdXqso9vjLmG0MqaBm3GbgkZmagyUdJVXIYW9h73i2+oK9zDIfjo4N1XqmaQpyttU
          oUqop2tjN3ZrDyzptGY8NExz83nN7gdGgVNbzBQXt+uJvTPoCUCseUz6vArwdUhnGNecG
          DryIAD7qW1/DEPYtDKcRTaGsrzs5VPaXGPclqMdfQ91ZXc7wu0IdKZnwY3ut3Y=
      clientSecret: !encrypted/pkcs1-oaep
        - OBLUEviqd7iJ1Nvns/rRr77PKqfdxKrfwpno6I0e1AWXZzN7563m+es8pYUb5L8xfaiEL
          amfj3Qap+6X7vhnqBaY3xJk8o40qQD0n2nxldq5nJtL5750ezCCJ/ZgqaNkX4VW4rdbAx
          73f3PPiFR15INr+zH3fp1qfyNN6X+EyA1scm7z+YwM0Iz4z7WpJzWFvh/4ogBcfrICIks
          14QXA+pCj/OQVzGdSnaXnXPNjXkwfJl7/tr6uD5pHag2glTjiBJAbyf+UT/HBMefGURCT
          oltHMcZEXP344myTp0xfQYLk2Ul9pe53Vy+7MRsTSbnFH6H9BeeB+L7AKn4dQtOX6SqQP
          Nv7IRNlj54aOo6P/WVjznnQrBg18ALABMZmE1Sl4dcwqum+cdnBcZE4o0jw6zA7RVAxTZ
          /4rRBWBT6AU3KVxVxbZghlPXOe8D+P3mM8W8iR8lIYgQ2OQBDHkO7fjioyKocG/JIfR3e
          giKVf1LcT+z57GLHn9svlDfY8uiDdTl9zVrKGtXDEcgqZNJ4vShOZB0yG7FpyB9Afjp1P
          ATjWbR8rWTRsb34RXHmuGSo7P+LeDbAwrktWOAjCwQK8q6ZyAvt8GGY3L1RdUtSvH4hiu
          tFQ4NuvXbvBr/sUTysOYhtjqTZaEcnXb7fJfizuzADRM9qRqkWRQe3UEiN3paA=
      refreshToken: !encrypted/pkcs1-oaep
        - INsTzgtTx9qRtfuBABU/O2Er3yXEK/Cj0dZ25o11Q74zVRCtWnE+sjoHVrsW/1xleCttq
          8XPHH1wO0AxqRrGNuN2Hzqrp4CoP0+ExUBVF1wQHvsyBXEtM8i9yY8KT4ijG9A7SRz0RI
          C02SnpNPVfPfga1fAB/ofofORtEqBVHyQArwPy+BvFSjqM1EdHxDH6pkHOtIEcUkGU/Wh
          eITT7l/H9WpXNubObeiQi9XBwGDXVC/+b77M3+RXwJijwW4X2EHu1Uu/y4xTaUMRxkANH
          rQ+UMoZpfQajVkrovksY6CRUa+N98M3Y6rf/TlY55DDAyS3sr2OVaqGDVhogqZ036gb67
          dx6T4+ReEWmj08CPnXDT6leerOXOJF7dwhBeXZzOwA6wreKiyhS5Suoiczaarq+uzwZxc
          eZQwcXVo3Gc+aK4yvzFGv+0s1cIVqgeD48aE/JxUIearJDRNeZwt4sxPAxJpMRuavbvFf
          FvBXSpCSFFpjl/pWxtkzz1vU4xcjO9SpcqTyfdyjkOzGCKsmU8EGRx9IR95sgo5/Xx18Y
          94l7EVztYIzxHxFmjCy7kkBGJbjnu+gzwm/bobFfH+Pu8R0YgbRVh9RN1JcWqW19cxl49
          FA/JgM+xJB3xF3feq4xbxHJy3sABC6QidTfWu7xPRhituhAS1kA8xuIEUdUgrQ=
